ticket-2.2/ProfilCreation_GeneralCondition & ProfilCreation_Fancreato…
bantubeat/saloonprived_app_ui pull request #17
Opened 2024-10-18 06:41 UTC by BIDIASNOHO

![localhost_50074_(iPad Mini) (1)](https://github.com/user-attachments/assets/c145773b-729d-4d97-9d8b-9e908ea7b675)
![localhost_50074_(Pixel 7) (1)](https://github.com/user-attachments/assets/9ca30623-674e-4f4a-8802-d1754c0d5464)
![localhost_50074_(iPhone SE) (1)](https://github.com/user-attachments/assets/f33c394f-a66f-4954-b84a-73db88300041)
![localhost_50074_(iPad Mini)](https://github.com/user-attachments/assets/489e8f0e-e65c-4e4b-8d60-cffb0d423b11)
![localhost_50074_(Pixel 7)](https://github.com/user-attachments/assets/d349122a-e148-4d6f-aaf0-ee2ccc0bd952)
![localhost_50074_(iPhone SE)](https://github.com/user-attachments/assets/ea17ab0c-d75c-4c9e-a5aa-c61d3d94806e)

2024-10-20 05:28 UTC, Mezatsong requested changes
Je vois que la table des matières que tu as ajouté je ne retrouve pas ça dans le design, dit moi, ce sont réellement les meme texte ??
et aussi tu n'a pas fait la correction que le boss a demandé, sinon tu n'a pas fait de capture d'écran

2024-10-20 05:28 UTC, Mezatsong commented on lib/src/screens/ProfilCreation_GeneralCondition_screen/profilcreation_generalcondition_screen.dart
Le nom des fichiers est en **snake_case** et les nom des dossiers aussi

Exemple:
**profile_creation_general_condition/profile_creation_general_condition.dart** 

Li le README stp, les conventions sont bien écrite laba

2024-10-20 05:28 UTC, Mezatsong commented on lib/src/components/my_button.dart
> +// lib/src/components/my_button.dart
Supprime le commentaire

2024-10-20 07:49 UTC, BIDIASNOHO commented
> Je vois que la table des matières que tu as ajouté je ne retrouve pas ça dans le design, dit moi, ce sont réellement les meme texte ?? et aussi tu n'a pas fait la correction que le boss a demandé, sinon tu n'a pas fait de capture d'écran

dans la pr le design qui est là n'est qu'une portion des texte qui se trouvent sur le site de bantubeat, et dans la pr c'est spécifié que le texte originale se trouve la bas, donc vérifie bien tu verra que c'est le texte complet officiel qui est sur mes vue, et oui j'ai corrigé mais  je n'ai plus refait de capture, en corrigeant les details la je vais capturer

2024-10-24 05:32 UTC, Mezatsong approved these changes
Le nom des dossiers sont aussi en snake_case, je merge juste pour ne pas perdre plus de temps mais les prochain ticket veille à ça

2024-10-24 05:35 UTC, merged