Ticket 2.1/profile creation screen
bantubeat/saloonprived_app_ui pull request #3
Opened 2024-10-16 06:38 UTC by ARROKO

lien du ticket : [](https://trello.com/c/T5kk8MjO/27-21-cr%C3%A9ation-profil-page-bienvenue )

1. iPhone SE
![IPhone SE](https://github.com/user-attachments/assets/aa85ee45-d62b-418d-8bef-66156da5b027)

3. Pixel 7
![Pixel 7](https://github.com/user-attachments/assets/0b39f1f5-d4d2-4bb0-9043-b00a24a034dc)

5. iPad mini
![iPad Mini](https://github.com/user-attachments/assets/35442cce-b1ab-43d0-acf1-2349ddf786bf)

2024-10-17 14:57 UTC, Mezatsong requested changes
Evite de créé c genre de PR, quand tu finis un ticket,
revient sur **main** tu fais un **git pull origin main** et tu créé une nouvelle branche a partir de là pour le nouveau ticket

2024-10-17 14:57 UTC, Mezatsong commented on lib/src/resources/app_assets.dart
> +  static const fakeAvatarImage = 'assets/images/fake_avatar.jpg';
```suggestion
  static const imagesFakeAvatar = 'assets/images/fake_avatar.jpg';
```
ça doit respecter la convention qui est de reprendre le nom du fichier mais en camelCase (sauf assets et l'extension)

2024-10-17 14:57 UTC, Mezatsong commented on lib/src/screens/profile_creation/category_screen.dart
> +
Deplace ça dans dans un sous dossier widgets du dossier de sa screen

2024-10-17 14:57 UTC, Mezatsong commented on lib/src/screens/profile_creation/category_screen.dart
> +
Créé un dossier **profile_creation_category* et place ton fichier en tant que *profile_creation_category_screen.dart*

2024-10-17 14:57 UTC, Mezatsong commented on lib/src/screens/profile_creation/category_screen.dart
> +                                ),
ça doit être internationalisé

2024-10-17 14:57 UTC, Mezatsong commented on lib/src/screens/profile_creation/category_screen.dart
> +                                  "*Vous ne pouvez choisir qu'une seule catégorie, si vous souhaitez devenir créateur saloonprived, selectionnez réellement la catégorie qui s'identifie au mieux au st
ça doit être internationalisé

2024-10-20 05:15 UTC, Mezatsong commented
Fait d'abord en sorte que le CI/CD n'échoue plus

2024-10-20 05:19 UTC, Mezatsong requested changes
1. Si je merge ton ticket ça supprimer la screen notification, je ne peux donc la mergé, je te conseil de crééer une toute nouvelle PR et de copier coller ton travail

2. Le ticket ci est à recommencé tu ne respecte aucune convention sur les noms de fichier ou sur la structure des dossier

2024-10-20 05:19 UTC, Mezatsong commented on lib/src/screens/profile_creation/profile_creation_category/category_screen.dart
tu ne respecte aucune convention toi, **profile_creation_category_screen.dart**
dis moi, tu as lu le README du projet ??

2024-10-21 15:51 UTC, ARROKO commented on lib/src/screens/profile_creation/category_screen.dart
> +
j'ai d retirer ce screen vu qu'il y a une branche speciale pour lui, j'ai effectuer ces modifs la bas

2024-10-21 15:55 UTC, ARROKO commented on lib/src/screens/profile_creation/category_screen.dart
> +
J'ai fais un pull vers la branche principale et du coup j'ai utiliser le widget général primaryButton donc j'ai retirer celui ci

2024-10-21 15:55 UTC, ARROKO commented on lib/src/screens/profile_creation/category_screen.dart
> +                                ),
C'est fait

2024-10-21 15:55 UTC, ARROKO commented on lib/src/screens/profile_creation/category_screen.dart
> +                                  "*Vous ne pouvez choisir qu'une seule catégorie, si vous souhaitez devenir créateur saloonprived, selectionnez réellement la catégorie qui s'identifie au mieux au st
C'est fait

2024-10-21 15:56 UTC, ARROKO commented on lib/src/resources/app_assets.dart
> +  static const fakeAvatarImage = 'assets/images/fake_avatar.jpg';
J'ai retirer ce code je ne l'utilisait pas pour cette branche actuelle

2024-10-27 19:37 UTC, Mezatsong approved these changes

2024-10-27 19:47 UTC, merged